hibernate:
    connection:
        autocommit: true


spring:
    datasource:
        driver-class-name: org.sqlite.JDBC
        url: jdbc:sqlite:addressbook.db
    jpa:
        database-platform: com.pesahlavan.training.javafx.dialect.SQLiteDialect
        properties:
            hibernate:
                current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
                format_sql: true
        show-sql: true

logging:
    level:
        ROOT: WARN
        org.springframework: debug
        org.hibernate: debug
        org.hibernate.type.descriptor.sql: trace

    pattern:
        console: '%d{HH:mm:ss} %-5p [%c]  -   %m%n'
    file: C:\Work\Idea15\javabegin.ru\AdrBook_SpringBoot_JFX\app.log